max-gamma = 150

# Day profile: Returns screen to native colors
profile {
    time = 06:00
    identity = true
}

# Night Profile: Applies a cooler white filter with reduced intensity
profile {
    time = 21:00
    temperature = 5500
    gamma = 0.8
}